#include "inc/flash_type.h"

#include <assert.h>
#include <string.h>

#include "primary/can-primary.h"

uint16_t tx_ids[FLASH_TYPE_COUNT];
uint16_t rx_ids[FLASH_TYPE_COUNT];
uint16_t jump_ids[FLASH_TYPE_COUNT];
uint16_t request_ids[FLASH_TYPE_COUNT];
uint16_t response_ids[FLASH_TYPE_COUNT];

char *flash_type_name(FLASH_TYPE value) {
  switch (value) {
  case FLASH_TYPE_BMS_HV:
    return "BMS_HV";
  case FLASH_TYPE_BMS_CELLBOARD_0:
    return "BMS_CELLBOARD_0";
  case FLASH_TYPE_BMS_CELLBOARD_1:
    return "BMS_CELLBOARD_1";
  case FLASH_TYPE_BMS_CELLBOARD_2:
    return "BMS_CELLBOARD_2";
  case FLASH_TYPE_BMS_CELLBOARD_3:
    return "BMS_CELLBOARD_3";
  case FLASH_TYPE_BMS_CELLBOARD_4:
    return "BMS_CELLBOARD_4";
  case FLASH_TYPE_BMS_CELLBOARD_5:
    return "BMS_CELLBOARD_5";
  case FLASH_TYPE_BMS_CELLBOARD_ALL:
    return "BMS_CELLBOARD_ALL";
  case FLASH_TYPE_BMS_LV:
    return "BMS_LV";
  case FLASH_TYPE_BMS_LV_BLT:
    return "BMS_LV_BLT";
  case FLASH_TYPE_ECU:
    return "ECU";
  case FLASH_TYPE_STEERING:
    return "STEERING";
  case FLASH_TYPE_ACQUISINATOR_0:
    return "ACQUISINATOR_0";
  case FLASH_TYPE_ACQUISINATOR_1:
    return "ACQUISINATOR_1";
  case FLASH_TYPE_ACQUISINATOR_2:
    return "ACQUISINATOR_2";
  case FLASH_TYPE_ACQUISINATOR_3:
    return "ACQUISINATOR_3";
  case FLASH_TYPE_ACQUISINATOR_4:
    return "ACQUISINATOR_4";
  case FLASH_TYPE_ACQUISINATOR_5:
    return "ACQUISINATOR_5";
  case FLASH_TYPE_ACQUISINATOR_6:
    return "ACQUISINATOR_6";
  case FLASH_TYPE_ACQUISINATOR_7:
    return "ACQUISINATOR_7";
  case FLASH_TYPE_ACQUISINATOR_8:
    return "ACQUISINATOR_8";
  case FLASH_TYPE_ACQUISINATOR_9:
    return "ACQUISINATOR_9";
  case FLASH_TYPE_ACQUISINATOR_10:
    return "ACQUISINATOR_10";
  case FLASH_TYPE_ACQUISINATOR_11:
    return "ACQUISINATOR_11";
  case FLASH_TYPE_ACQUISINATOR_12:
    return "ACQUISINATOR_12";
  case FLASH_TYPE_ACQUISINATOR_13:
    return "ACQUISINATOR_13";
  case FLASH_TYPE_ACQUISINATOR_14:
    return "ACQUISINATOR_14";
  case FLASH_TYPE_ACQUISINATOR_15:
    return "ACQUISINATOR_15";
  case FLASH_TYPE_ACQUISINATOR_16:
    return "ACQUISINATOR_16";
  case FLASH_TYPE_ACQUISINATOR_17:
    return "ACQUISINATOR_17";
  case FLASH_TYPE_ACQUISINATOR_18:
    return "ACQUISINATOR_18";
  case FLASH_TYPE_ACQUISINATOR_19:
    return "ACQUISINATOR_19";
  case FLASH_TYPE_ACQUISINATOR_20:
    return "ACQUISINATOR_20";
  case FLASH_TYPE_ACQUISINATOR_21:
    return "ACQUISINATOR_21";
  case FLASH_TYPE_ACQUISINATOR_22:
    return "ACQUISINATOR_22";
  case FLASH_TYPE_ACQUISINATOR_23:
    return "ACQUISINATOR_23";
  case FLASH_TYPE_ACQUISINATOR_24:
    return "ACQUISINATOR_24";
  case FLASH_TYPE_ACQUISINATOR_25:
    return "ACQUISINATOR_25";
  case FLASH_TYPE_ACQUISINATOR_26:
    return "ACQUISINATOR_26";
  case FLASH_TYPE_ACQUISINATOR_27:
    return "ACQUISINATOR_27";
  case FLASH_TYPE_ACQUISINATOR_28:
    return "ACQUISINATOR_28";
  case FLASH_TYPE_ACQUISINATOR_29:
    return "ACQUISINATOR_29";
  case FLASH_TYPE_ACQUISINATOR_30:
    return "ACQUISINATOR_30";
  case FLASH_TYPE_ACQUISINATOR_31:
    return "ACQUISINATOR_31";
  default:
    return "\0";
  }
}
FLASH_TYPE flash_type_value(const char *name) {
  if (strcmp(name, "BMS_HV") == 0) {
    return FLASH_TYPE_BMS_HV;
  } else if (strcmp(name, "BMS_CELLBOARD_0") == 0) {
    return FLASH_TYPE_BMS_CELLBOARD_0;
  } else if (strcmp(name, "BMS_CELLBOARD_1") == 0) {
    return FLASH_TYPE_BMS_CELLBOARD_1;
  } else if (strcmp(name, "BMS_CELLBOARD_2") == 0) {
    return FLASH_TYPE_BMS_CELLBOARD_2;
  } else if (strcmp(name, "BMS_CELLBOARD_3") == 0) {
    return FLASH_TYPE_BMS_CELLBOARD_3;
  } else if (strcmp(name, "BMS_CELLBOARD_4") == 0) {
    return FLASH_TYPE_BMS_CELLBOARD_4;
  } else if (strcmp(name, "BMS_CELLBOARD_5") == 0) {
    return FLASH_TYPE_BMS_CELLBOARD_5;
  } else if (strcmp(name, "BMS_CELLBOARD_ALL") == 0) {
    return FLASH_TYPE_BMS_CELLBOARD_ALL;
  } else if (strcmp(name, "BMS_LV") == 0) {
    return FLASH_TYPE_BMS_LV;
  } else if (strcmp(name, "BMS_LV_BLT") == 0) {
    return FLASH_TYPE_BMS_LV_BLT;
  } else if (strcmp(name, "ECU") == 0) {
    return FLASH_TYPE_ECU;
  } else if (strcmp(name, "STEERING") == 0) {
    return FLASH_TYPE_STEERING;
  } else if (strcmp(name, "ACQUISINATOR_0") == 0) {
    return FLASH_TYPE_ACQUISINATOR_0;
  } else if (strcmp(name, "ACQUISINATOR_1") == 0) {
    return FLASH_TYPE_ACQUISINATOR_1;
  } else if (strcmp(name, "ACQUISINATOR_2") == 0) {
    return FLASH_TYPE_ACQUISINATOR_2;
  } else if (strcmp(name, "ACQUISINATOR_3") == 0) {
    return FLASH_TYPE_ACQUISINATOR_3;
  } else if (strcmp(name, "ACQUISINATOR_4") == 0) {
    return FLASH_TYPE_ACQUISINATOR_4;
  } else if (strcmp(name, "ACQUISINATOR_5") == 0) {
    return FLASH_TYPE_ACQUISINATOR_5;
  } else if (strcmp(name, "ACQUISINATOR_6") == 0) {
    return FLASH_TYPE_ACQUISINATOR_6;
  } else if (strcmp(name, "ACQUISINATOR_7") == 0) {
    return FLASH_TYPE_ACQUISINATOR_7;
  } else if (strcmp(name, "ACQUISINATOR_8") == 0) {
    return FLASH_TYPE_ACQUISINATOR_8;
  } else if (strcmp(name, "ACQUISINATOR_9") == 0) {
    return FLASH_TYPE_ACQUISINATOR_9;
  } else if (strcmp(name, "ACQUISINATOR_10") == 0) {
    return FLASH_TYPE_ACQUISINATOR_10;
  } else if (strcmp(name, "ACQUISINATOR_11") == 0) {
    return FLASH_TYPE_ACQUISINATOR_11;
  } else if (strcmp(name, "ACQUISINATOR_12") == 0) {
    return FLASH_TYPE_ACQUISINATOR_12;
  } else if (strcmp(name, "ACQUISINATOR_13") == 0) {
    return FLASH_TYPE_ACQUISINATOR_13;
  } else if (strcmp(name, "ACQUISINATOR_14") == 0) {
    return FLASH_TYPE_ACQUISINATOR_14;
  } else if (strcmp(name, "ACQUISINATOR_15") == 0) {
    return FLASH_TYPE_ACQUISINATOR_15;
  } else if (strcmp(name, "ACQUISINATOR_16") == 0) {
    return FLASH_TYPE_ACQUISINATOR_16;
  } else if (strcmp(name, "ACQUISINATOR_17") == 0) {
    return FLASH_TYPE_ACQUISINATOR_17;
  } else if (strcmp(name, "ACQUISINATOR_18") == 0) {
    return FLASH_TYPE_ACQUISINATOR_18;
  } else if (strcmp(name, "ACQUISINATOR_19") == 0) {
    return FLASH_TYPE_ACQUISINATOR_19;
  } else if (strcmp(name, "ACQUISINATOR_20") == 0) {
    return FLASH_TYPE_ACQUISINATOR_20;
  } else if (strcmp(name, "ACQUISINATOR_21") == 0) {
    return FLASH_TYPE_ACQUISINATOR_21;
  } else if (strcmp(name, "ACQUISINATOR_22") == 0) {
    return FLASH_TYPE_ACQUISINATOR_22;
  } else if (strcmp(name, "ACQUISINATOR_23") == 0) {
    return FLASH_TYPE_ACQUISINATOR_23;
  } else if (strcmp(name, "ACQUISINATOR_24") == 0) {
    return FLASH_TYPE_ACQUISINATOR_24;
  } else if (strcmp(name, "ACQUISINATOR_25") == 0) {
    return FLASH_TYPE_ACQUISINATOR_25;
  } else if (strcmp(name, "ACQUISINATOR_26") == 0) {
    return FLASH_TYPE_ACQUISINATOR_26;
  } else if (strcmp(name, "ACQUISINATOR_27") == 0) {
    return FLASH_TYPE_ACQUISINATOR_27;
  } else if (strcmp(name, "ACQUISINATOR_28") == 0) {
    return FLASH_TYPE_ACQUISINATOR_28;
  } else if (strcmp(name, "ACQUISINATOR_29") == 0) {
    return FLASH_TYPE_ACQUISINATOR_29;
  } else if (strcmp(name, "ACQUISINATOR_30") == 0) {
    return FLASH_TYPE_ACQUISINATOR_30;
  } else if (strcmp(name, "ACQUISINATOR_31") == 0) {
    return FLASH_TYPE_ACQUISINATOR_31;
  }
  return FLASH_TYPE_COUNT;
}

void setup_flash_ids() {
  tx_ids[FLASH_TYPE_BMS_HV] = CAN_PRIMARY_MESSAGE_FRAME_ID_HV_BMS_MAINBOARD_RX;
  rx_ids[FLASH_TYPE_BMS_HV] = CAN_PRIMARY_MESSAGE_FRAME_ID_HV_BMS_MAINBOARD_TX;
  jump_ids[FLASH_TYPE_BMS_HV] = CAN_PRIMARY_MESSAGE_FRAME_ID_HV_BMS_FLASH;
  request_ids[FLASH_TYPE_BMS_HV] = UINT16_MAX;
  response_ids[FLASH_TYPE_BMS_HV] = UINT16_MAX;

  tx_ids[FLASH_TYPE_BMS_CELLBOARD_0] =
      CAN_PRIMARY_MESSAGE_FRAME_ID_HV_BMS_CELLBOARD_OPENBLT_RX_0;
  rx_ids[FLASH_TYPE_BMS_CELLBOARD_0] =
      CAN_PRIMARY_MESSAGE_FRAME_ID_HV_BMS_CELLBOARD_OPENBLT_TX_0;
  jump_ids[FLASH_TYPE_BMS_CELLBOARD_0] =
      CAN_PRIMARY_MESSAGE_FRAME_ID_HV_BMS_FLASH;
  request_ids[FLASH_TYPE_BMS_CELLBOARD_0] = UINT16_MAX;
  response_ids[FLASH_TYPE_BMS_CELLBOARD_0] = UINT16_MAX;

  tx_ids[FLASH_TYPE_BMS_CELLBOARD_1] =
      CAN_PRIMARY_MESSAGE_FRAME_ID_HV_BMS_CELLBOARD_OPENBLT_RX_1;
  rx_ids[FLASH_TYPE_BMS_CELLBOARD_1] =
      CAN_PRIMARY_MESSAGE_FRAME_ID_HV_BMS_CELLBOARD_OPENBLT_TX_1;
  jump_ids[FLASH_TYPE_BMS_CELLBOARD_1] =
      CAN_PRIMARY_MESSAGE_FRAME_ID_HV_BMS_FLASH;
  request_ids[FLASH_TYPE_BMS_CELLBOARD_1] = UINT16_MAX;
  response_ids[FLASH_TYPE_BMS_CELLBOARD_1] = UINT16_MAX;

  tx_ids[FLASH_TYPE_BMS_CELLBOARD_2] =
      CAN_PRIMARY_MESSAGE_FRAME_ID_HV_BMS_CELLBOARD_OPENBLT_RX_2;
  rx_ids[FLASH_TYPE_BMS_CELLBOARD_2] =
      CAN_PRIMARY_MESSAGE_FRAME_ID_HV_BMS_CELLBOARD_OPENBLT_TX_2;
  jump_ids[FLASH_TYPE_BMS_CELLBOARD_2] =
      CAN_PRIMARY_MESSAGE_FRAME_ID_HV_BMS_FLASH;
  request_ids[FLASH_TYPE_BMS_CELLBOARD_2] = UINT16_MAX;
  response_ids[FLASH_TYPE_BMS_CELLBOARD_2] = UINT16_MAX;

  tx_ids[FLASH_TYPE_BMS_CELLBOARD_3] =
      CAN_PRIMARY_MESSAGE_FRAME_ID_HV_BMS_CELLBOARD_OPENBLT_RX_3;
  rx_ids[FLASH_TYPE_BMS_CELLBOARD_3] =
      CAN_PRIMARY_MESSAGE_FRAME_ID_HV_BMS_CELLBOARD_OPENBLT_TX_3;
  jump_ids[FLASH_TYPE_BMS_CELLBOARD_3] =
      CAN_PRIMARY_MESSAGE_FRAME_ID_HV_BMS_FLASH;
  request_ids[FLASH_TYPE_BMS_CELLBOARD_3] = UINT16_MAX;
  response_ids[FLASH_TYPE_BMS_CELLBOARD_3] = UINT16_MAX;

  tx_ids[FLASH_TYPE_BMS_CELLBOARD_4] =
      CAN_PRIMARY_MESSAGE_FRAME_ID_HV_BMS_CELLBOARD_OPENBLT_RX_4;
  rx_ids[FLASH_TYPE_BMS_CELLBOARD_4] =
      CAN_PRIMARY_MESSAGE_FRAME_ID_HV_BMS_CELLBOARD_OPENBLT_TX_4;
  jump_ids[FLASH_TYPE_BMS_CELLBOARD_4] =
      CAN_PRIMARY_MESSAGE_FRAME_ID_HV_BMS_FLASH;
  request_ids[FLASH_TYPE_BMS_CELLBOARD_4] = UINT16_MAX;
  response_ids[FLASH_TYPE_BMS_CELLBOARD_4] = UINT16_MAX;

  tx_ids[FLASH_TYPE_BMS_CELLBOARD_5] =
      CAN_PRIMARY_MESSAGE_FRAME_ID_HV_BMS_CELLBOARD_OPENBLT_RX_5;
  rx_ids[FLASH_TYPE_BMS_CELLBOARD_5] =
      CAN_PRIMARY_MESSAGE_FRAME_ID_HV_BMS_CELLBOARD_OPENBLT_TX_5;
  jump_ids[FLASH_TYPE_BMS_CELLBOARD_5] =
      CAN_PRIMARY_MESSAGE_FRAME_ID_HV_BMS_FLASH;
  request_ids[FLASH_TYPE_BMS_CELLBOARD_5] = UINT16_MAX;
  response_ids[FLASH_TYPE_BMS_CELLBOARD_5] = UINT16_MAX;

  tx_ids[FLASH_TYPE_BMS_CELLBOARD_ALL] = UINT16_MAX;
  rx_ids[FLASH_TYPE_BMS_CELLBOARD_ALL] = UINT16_MAX;
  jump_ids[FLASH_TYPE_BMS_CELLBOARD_ALL] =
      CAN_PRIMARY_MESSAGE_FRAME_ID_HV_BMS_FLASH;
  request_ids[FLASH_TYPE_BMS_CELLBOARD_ALL] = UINT16_MAX;
  response_ids[FLASH_TYPE_BMS_CELLBOARD_ALL] = UINT16_MAX;

  tx_ids[FLASH_TYPE_STEERING] =
      CAN_PRIMARY_MESSAGE_FRAME_ID_STEERING_WHEEL_OPENBLT_RX;
  rx_ids[FLASH_TYPE_STEERING] =
      CAN_PRIMARY_MESSAGE_FRAME_ID_STEERING_WHEEL_OPENBLT_TX;
  jump_ids[FLASH_TYPE_STEERING] =
      CAN_PRIMARY_MESSAGE_FRAME_ID_STEERING_WHEEL_FLASH;
  request_ids[FLASH_TYPE_STEERING] = UINT16_MAX;
  response_ids[FLASH_TYPE_STEERING] = UINT16_MAX;
}

bool is_can_primary(FLASH_TYPE flash_device) {
  switch (flash_device) {
  case FLASH_TYPE_BMS_HV:
  case FLASH_TYPE_BMS_CELLBOARD_0:
  case FLASH_TYPE_BMS_CELLBOARD_1:
  case FLASH_TYPE_BMS_CELLBOARD_2:
  case FLASH_TYPE_BMS_CELLBOARD_3:
  case FLASH_TYPE_BMS_CELLBOARD_4:
  case FLASH_TYPE_BMS_CELLBOARD_5:
  case FLASH_TYPE_BMS_CELLBOARD_ALL:
  case FLASH_TYPE_BMS_LV:
  case FLASH_TYPE_BMS_LV_BLT:
  case FLASH_TYPE_ECU:
  case FLASH_TYPE_STEERING:
    return true;
  case FLASH_TYPE_ACQUISINATOR_0:
  case FLASH_TYPE_ACQUISINATOR_1:
  case FLASH_TYPE_ACQUISINATOR_2:
  case FLASH_TYPE_ACQUISINATOR_3:
  case FLASH_TYPE_ACQUISINATOR_4:
  case FLASH_TYPE_ACQUISINATOR_5:
  case FLASH_TYPE_ACQUISINATOR_6:
  case FLASH_TYPE_ACQUISINATOR_7:
  case FLASH_TYPE_ACQUISINATOR_8:
  case FLASH_TYPE_ACQUISINATOR_9:
  case FLASH_TYPE_ACQUISINATOR_10:
  case FLASH_TYPE_ACQUISINATOR_11:
  case FLASH_TYPE_ACQUISINATOR_12:
  case FLASH_TYPE_ACQUISINATOR_13:
  case FLASH_TYPE_ACQUISINATOR_14:
  case FLASH_TYPE_ACQUISINATOR_15:
  case FLASH_TYPE_ACQUISINATOR_16:
  case FLASH_TYPE_ACQUISINATOR_17:
  case FLASH_TYPE_ACQUISINATOR_18:
  case FLASH_TYPE_ACQUISINATOR_19:
  case FLASH_TYPE_ACQUISINATOR_20:
  case FLASH_TYPE_ACQUISINATOR_21:
  case FLASH_TYPE_ACQUISINATOR_22:
  case FLASH_TYPE_ACQUISINATOR_23:
  case FLASH_TYPE_ACQUISINATOR_24:
  case FLASH_TYPE_ACQUISINATOR_25:
  case FLASH_TYPE_ACQUISINATOR_26:
  case FLASH_TYPE_ACQUISINATOR_27:
  case FLASH_TYPE_ACQUISINATOR_28:
  case FLASH_TYPE_ACQUISINATOR_29:
  case FLASH_TYPE_ACQUISINATOR_30:
  case FLASH_TYPE_ACQUISINATOR_31:
    return false;
  default:
    assert(false && "Can interface is not specified");
  }
}
